### ISSUE TITLE
Regarding the issue of not treating reserved words (sections) as reserved words

### ISSUE THREAD

**Issue by KT1061** [krisds/koopa#33]
Hello krisds.
I am creating my own kg file.
An analysis error occurred when analyzing the sample code with this kg file.

My expectation is that "a01 section" in the source code should be treated as a section heading (the def section part of the kg file).
However, in the actual analysis result, the corresponding part is processed as a paragraph name (the def paragraph part of the kg file).

We believe this is because section cannot be treated as a reserved word, so it is treated as a paragraph name.

How can I prevent it from being treated as a paragraph name by treating section as a reserved word?

[KT1061.zip](https://github.com/krisds/koopa/files/12697350/KT1061.zip)

**Comment by krisds** [comment]
OK, so I see two possible solutions, with different impacts.

First, let me try to explain what's going wrong. So you have:

```
def paragraph =
    paragraphName [.]
    (sentence)*
end
```

while trying to process `( paragraph )*` in `procedureDivision_format1`.

What happens when you see an input "a1 SECTION." ?

It will first match "a1" to the paragraph name. Then look for an optional ".", and not find one. Then look for a number of sentences, and not find any.

Next it will try to match another paragraph. It sees "SECTION." and matches "SECTION" as the paragraph name (which is allowed here, as SECTION as a keyword is not relevant at this position). Next it matches the optional ".".

So "a1 SECTION." is seen as two paragraphs, "a1" and "SECTION".

I see (and tried) two possible solutions.

The first is to make the "." after the paragraph name not optional (as it is in the Cobol.kg grammar):


```
def paragraph =
    paragraphName .
    (sentence)*
end
```

That will break the first paragraph match. But, it means every paragraph name must be followed by a ".". Given that you changed this, I'm guessing that may not be what you want.

So the second option is to explicitly tell the grammar that a paragraph name may not be followed by "SECTION":

```
def paragraph =
    paragraphName (%not SECTION) [.]
    (sentence)*
end
```

This too will break the match as a paragraph, but will leave the "." optional.

Which is the better option ? If you need the "." to be optional, then the second is the only way to do it. If it's not optional then I feel the first is cleaner.

Hope this helps.

PS. You can enable grammar logging in the UI, and that will (in deep detail) print out the whole matching process. It takes some getting used to, but it is very helpful in trying to figure out where a match is breaking down.

**Comment by KT1061** [comment]
I was able to deal with it using the second solution.
thank you.

**Comment by krisds** [comment]
👍
